blueprint:
  name: Power control timer
  description: "Timer to control a switch, powering things like lights or electric blankets etc. Controlled by start and stop buttons."
  domain: automation

  input:
    power:
      name: The switch ontrolling the power to the device
      selector:
        entity:
          filter:
            domain: switch
    start_button:
      name: The button to start and increment the timer
      selector:
        entity:
          filter:
            domain: input_button
    clear_button:
      name: The button to stop the timer
      selector:
        entity:
          filter:
            domain: input_button
    timer:
      name: The timer to control the power switch
      selector:
        entity:
          filter:
            domain: timer

    timer_inc:
      name: Timer increment step in seconds
      default: 3600
      selector:
        number:
          min: 10
          max: 3600
    timer_max_inc: 
      name: Maximum timer increments permitted
      default: 5
      selector:
        number:
          min: 1
          max: 10

mode: queued

trigger:
  - platform: state
    entity_id: !input power
    to: 'on'
    id: switch_to_on
  - platform: state
    entity_id: !input power
    to: 'off'
    id: button_clear
  - platform: state
    entity_id: !input start_button
    id: button_start
  - platform: state
    entity_id: !input clear_button
    id: button_clear
  - platform: event
    id: timer_stop
    event_type:
      - timer.cancelled
      - timer.finished
    event_data:
      entity_id: !input timer
  - platform: event
    id: timer_start
    event_type:
      - timer.started
      - timer.restarted
    event_data:
      entity_id: !input timer

variables:
  power: !input power
  start_button: !input start_button
  clear_button: !input clear_button
  timer: !input timer
  timer_inc: !input timer_inc
  timer_max_inc:  !input timer_max_inc

action:
  - variables:
      timer_state: "{{ states(timer) }}"

  - choose:
      - conditions:
            # Switch has turned on, but timer not running. Just put an hour on the timer.
          - condition: trigger
            id: switch_to_on
          - condition: template
            value_template: "{{ 'idle' in timer_state  }}"
        sequence:
          - service: timer.start
            data:
              duration: "{{ timer_inc }}"
            target:
              entity_id: "{{ timer }}"

      - conditions:
          - condition: trigger
            id: button_start
        sequence:
          - variables:
              new_duration: >-
                {% set remaining = (state_attr(timer, 'finishes_at') | default(0, 1) | as_datetime - now()).total_seconds() %} 
                {% set duration = iif( remaining > 0, remaining|int + timer_inc, timer_inc) %}
                {{ min ([timer_max_inc * timer_inc, duration]) }}
          - service: timer.start
            data:
              duration: "{{ new_duration }}"
            target:
              entity_id: "{{ timer }}"
      - conditions:
          - condition: trigger
            id: button_clear
        sequence:
          - service: timer.cancel
            target:
              entity_id: "{{ timer }}"
      - conditions:
          - condition: trigger
            id: timer_start
        sequence:
          - service: switch.turn_on
            data: {}
            target:
              entity_id: "{{ power }}"
      - conditions:
          - condition: trigger
            id: timer_stop
        sequence:
          - service: switch.turn_off
            target:
              entity_id: "{{ power }}"
            data: {}

